### ISSUE TITLE
Windows version fails on folders with spaces in the name

### ISSUE THREAD

**Issue by hstraten** [giwty/switch-library-manager#32]
Startup fails when running from a folder with spaces in the name, like "E:\My Switch Tools\switch-library-manager"

error:
failed to create logger - couldn't open sink "winfile:///E:\\My Switch Tools\\switch-library-manager.windows\\slm.log": open E:\: is a directorypanic: 1

goroutine 1 [running]:
main.createLogger(0xc00001caf0, 0x44, 0xc000158700, 0xc0002dc150)
        /Users/twig/IdeaProjects/nsp-update/main.go:85 +0x416
main.main()
        /Users/twig/IdeaProjects/nsp-update/main.go:43 +0x1aa

**Comment by giwty** [comment]
Yeah, i need to better handle windows log file path, please just avoid spaces for now :)
